#!/bin/bash

set -e
set -x

apt-get update
apt-get install -qqy nginx esmtp-run unzip subversion libxml2 libcurl4-openssl-dev sqlite3 libsqlite3-dev wget curl php-cli php-dev php-sqlite3 php-mysql php-pgsql php-curl php-json php-gd php-fpm php-pear php-apcu php-intl php-xmlrpc php-imap php-mbstring php-zip php-imagick supervisor
apt-get clean -qq
rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# download latest wordpress
curl -sSL https://wordpress.org/latest.tar.gz | tar -C /var/www -xzf -
mv /var/www/wordpress /var/www/public
chown -R www-data:www-data /var/www/public
